---

- hosts: all
  become: true
  tasks:
    - name: update repository
      apt:
        update_cache: yes
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: install apache
      apt:
        name: apache2
        state: latest
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: add php support for apache
      apt:
        name: libapache2-mod-php
        state: latest
      when: ansible_distribution in ["Debian", "Ubuntu"]


    - name: update repository
      dnf:
        update_cache: yes
      when: ansible_distribution in ["CentOS"]

    - name: install apache
      dnf:
        name: httpd
        state: latest
      when: ansible_distribution in ["CentOS"]

    - name: add php support for apache
      dnf:
        name: php
        state: latest
      when: ansible_distribution in ["CentOS"]
