---

- hosts: all
  become: true
  tasks:
    - name: update repository
      apt:
        update_cache: yes

    - name: install apache
      apt:
        name: apache2
        state: absent

    - name: add php support for apache
      apt:
        name: libapache2-mod-php
        state: absent
